language: node_js
node_js: stable

# S: Build Lifecycle
install:
- npm install

script:
- hexo g

after_script:
- cd ./public
- git init
- git config user.name "aikaiqiang"
- git config user.email "akqdream@163.com"
- git add .
- git commit -m "Update Blog By TravisCI With Build ${TRAVIS_BUILD_NUMBER}"

# Coding Pages
- git push --force --quiet "https://aikaiqiang:${Coding_Token}@${CO_REF}" master:master
- git tag ${TRAVIS_BUILD_NUMBER} -a -m "Auto Taged By TravisCI With Build ${TRAVIS_BUILD_NUMBER}"
# Coding Pages
- git push --quiet "https://aikaiqiang:${Coding_Token}@${CO_REF}" master:master --tags

# Github Pages
- git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master
- git push --quiet "https://${CI_TOKEN}@${GH_REF}" master:master --tags

branches:
  only:
  - master

env:
  global:
  # Github Pages
  - GH_REF: github.com/aikaiqiang/aikaiqiang.github.io
  # Coding Pages
  - CO_REF: git.dev.tencent.com/aikaiqiang/blog.git
  - TRAVIS_BUILD_NUMBER: v0.0.6 # 版本号